### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by jacobq** [Dhaulagiri/ember-highcharts-sample-app#1]
http://ember-highcharts-sample-app.divshot.io/

> Site Unavailable
> 
> Divshot, the hosting provider for this website, has ceased operation as of December 22, 2015. Divshot > technology now powers Firebase Hosting.
> 
> If this is your website, please update your DNS to point to a new hosting provider!
> [So long, and thanks for everything!]

**Comment by Dhaulagiri** [comment]
@jacobq indeed that is the case.  I don't have any plans to fix this since this repo is very out of date, but you can always pull it down and run it locally to see how it works.
